### ISSUE TITLE
Duplicate chinese characters after switch language

### ISSUE THREAD

**Issue by tobiichi3227** [fcitx/fcitx5#1034] opened 2024-04-28 01:41 UTC
**Describe the bug**
Like title say

**To Reproduce**
1. Typing Chinese in anywhere.
2. Switch language to English after finish input.
3. The originally entered Chinese characters will appear repeatedly.

**Expected behavior**
There should be no duplicate Chinese characters.

**Desktop (please complete the following information):**
 - Desktop: KDE Plasma 6.0.4
 - Display server type:  Wayland
 - The output of fcitx5-diagnose if possible.
```
# 系統資訊：
1.  `uname -a`:

        Linux user-arch-linux 6.8.6-arch1-1 #1 SMP PREEMPT_DYNAMIC Tue, 16 Apr 2024 11:30:09 +0000 x86_64 GNU/Linux

2.  `lsb_release`:

    找不到 `lsb_release`。

3.  `/etc/lsb-release`:

    找不到 `/etc/lsb-release`。

4.  `/etc/os-release`:

        NAME="Arch Linux"
        PRETTY_NAME="Arch Linux"
        ID=arch
        BUILD_ID=rolling
        ANSI_COLOR="38;2;23;147;209"
        HOME_URL="https://archlinux.org/"
        DOCUMENTATION_URL="https://wiki.archlinux.org/"
        SUPPORT_URL="https://bbs.archlinux.org/"
        BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
        PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
        LOGO=archlinux-logo

5.  桌面環境：

    桌面環境為 `kde`。

6.  XDG 會話類型：

        XDG_SESSION_TYPE='wayland'

7.  Bash 版本：

        BASH_VERSION='5.2.26(1)-release'

# 環境：
1.  DISPLAY:

        DISPLAY=':0'


        WAYLAND_DISPLAY='wayland-0'

2.  鍵盤配置：

    1.  `setxkbmap`:

            WARNING: Running setxkbmap against an Xwayland server
            xkb_keymap {
            	xkb_keycodes  { include "evdev+aliases(qwerty)"	};
            	xkb_types     { include "complete"	};
            	xkb_compat    { include "complete"	};
            	xkb_symbols   { include "pc+us+inet(evdev)+capslock(swapescape)"	};
            	xkb_geometry  { include "pc(pc105)"	};
            };

    2.  `xprop`:

            _XKB_RULES_NAMES(STRING) = "evdev", "pc105", "us", "", "caps:swapescape"

3.  地區設定：

    1.  全部可用 locale：

            C
            C.utf8
            en_US.utf8
            ja_JP.utf8
            POSIX
            zh_TW.utf8

    2.  目前地區設定：

            LANG=zh_TW.UTF-8
            LC_CTYPE=zh_TW.UTF-8
            LC_NUMERIC=zh_TW.UTF-8
            LC_TIME=zh_TW.UTF-8
            LC_COLLATE=zh_TW.UTF-8
            LC_MONETARY=zh_TW.UTF-8
            LC_MESSAGES=zh_TW.UTF-8
            LC_PAPER=zh_TW.UTF-8
            LC_NAME=zh_TW.UTF-8
            LC_ADDRESS=zh_TW.UTF-8
            LC_TELEPHONE=zh_TW.UTF-8
            LC_MEASUREMENT=zh_TW.UTF-8
            LC_IDENTIFICATION=zh_TW.UTF-8
            LC_ALL=

4.  目錄：

    1.  家目錄：

            /home/user

    2.  `${XDG_CONFIG_HOME}`:

        環境變數 `XDG_CONFIG_HOME` 未設定。

        `XDG_CONFIG_HOME` 目前的值為 `~/.config` (`/home/user/.config`)。

    3.  Fcitx5 設定目錄：

        目前的 fcitx5 設定目錄為 `~/.config/fcitx5` (`/home/user/.config/fcitx5`)。

5.  目前使用者：

    此腳本以 user (1000) 執行。

# Fcitx 狀態：
1.  可執行檔：

    在 `/usr/bin/fcitx5` 找到了 fcitx5。

2.  版本：

    Fcitx 版本：`5.1.9`

3.  處理程序：

    找到 1 個 fcitx5 程序：

            816 fcitx5

4.  `fcitx5-remote`:

    `fcitx5-remote` 運作正常。

5.  DBus 介面：

    使用 `dbus-send`檢查 dbus。

    DBus 名稱 `org.fcitx.Fcitx5` 的擁有者是 `:1.21`。

    DBus 名稱 `org.fcitx.Fcitx5` PID 的擁有者是 `816`。

    來自 dbus 的除錯訊息：

           Group [wayland:] has 7 InputContext(s)
          IC [e57b82a11ed749aabcc5d61ccf55ccd6] program:thorium-browser frontend:wayland cap:472 focus:0
          IC [7112020cd5d642d98216d0427534e793] program:Alacritty frontend:wayland cap:100000072 focus:0
          IC [95254f4d32c841718ad81f3116628747] program:Alacritty frontend:wayland cap:100000072 focus:0
          IC [8f5ab4a4671a4613bd432551f0dbe521] program:vlc frontend:wayland cap:d0072 focus:0
          IC [39309a15233743d783526e23334d1c22] program:Alacritty frontend:wayland cap:100000072 focus:0
          IC [ab4717160eb24fc59a148c42c1c52cba] program:thorium-browser frontend:wayland cap:80072 focus:0
          IC [3db854ba2ed7495e85108948f52f72d1] program: frontend:wayland cap:100000072 focus:0
        Group [x11::0] has 0 InputContext(s)
        Input Context without group

# Fcitx 設定介面：
1.  設定工具封裝：

    在 `/usr/bin/fcitx5-configtool` 找到了 fcitx5-configtool。

2.  Qt 的設定介面：

    在 `/usr/bin/fcitx5-config-qt` 找到了 `fcitx5-config-qt`。

3.  KDE 的設定介面：

    **找不到 `kcmshell5`。**

# 前端設定：
本腳本所檢查之環境變數僅包含目前殼層的環境。仍可能出現您並未將環境套用至整個圖形桌面。您可以對某個無法正常工作的行程執行 `xargs -0 -L1 /proc/$PID/environ` 以檢查其實際環境變數。

## Xim:
1.  `${XMODIFIERS}`:

    環境變數 XMODIFIERS 正確地設定為「@im=fcitx」。
    從環境變數中取得的 Xim 伺服器名稱為 fcitx。

2.  在根視窗的 XIM_SERVERS：

    Xim 伺服器名稱與環境變數中設定的名稱相同。

## Qt:
1.  qt4 - `${QT4_IM_MODULE}`:

    **請設定環境變數 QT_IM_MODULE 到「fcitx」，使用您的發行版提供的工具或加入 `export QT_IM_MODULE=fcitx` 到您的 `~/.xprofile`。請參閱 [輸入法相關環境變數：QT_IM_MODULE](http://fcitx-im.org/wiki/Input_method_related_environment_variables#QT_IM_MODULE)。**

    **找不到 `fcitx5-qt4-immodule-probing`。**

2.  qt5 - `${QT_IM_MODULE}`:

    **請設定環境變數 QT_IM_MODULE 到「fcitx」，使用您的發行版提供的工具或加入 `export QT_IM_MODULE=fcitx` 到您的 `~/.xprofile`。請參閱 [輸入法相關環境變數：QT_IM_MODULE](http://fcitx-im.org/wiki/Input_method_related_environment_variables#QT_IM_MODULE)。**

    **如果您的混成器完全支持 qt5使用的 text-input 協議，您也可以使用 qt5 內置的 Wayland 模塊。**

    使用 fcitx5-qt5-immodule-probing 檢查目前環境下將被實際使用的輸入法模塊：

        QT_QPA_PLATFORM=wayland
        QT_IM_MODULE=
        IM_MODULE_CLASSNAME=QtWaylandClient::QWaylandInputContext

3.  qt6 - `${QT_IM_MODULE}`:

    **請設定環境變數 QT_IM_MODULE 到「fcitx」，使用您的發行版提供的工具或加入 `export QT_IM_MODULE=fcitx` 到您的 `~/.xprofile`。請參閱 [輸入法相關環境變數：QT_IM_MODULE](http://fcitx-im.org/wiki/Input_method_related_environment_variables#QT_IM_MODULE)。**

    **如果您的混成器完全支持 qt6使用的 text-input 協議，您也可以使用 qt6 內置的 Wayland 模塊。**

    使用 fcitx5-qt6-immodule-probing 檢查目前環境下將被實際使用的輸入法模塊：

        QT_QPA_PLATFORM=wayland
        QT_IM_MODULE=
        IM_MODULE_CLASSNAME=QtWaylandClient::QWaylandInputContext

4.  Qt IM 模組檔案：

    找到了 fcitx5 的 qt6 模組：`/usr/lib/fcitx5/qt6/libfcitx-quickphrase-editor5.so`。
    找到了 fcitx5 的 qt5 模組：`/usr/lib/fcitx5/qt5/libfcitx-quickphrase-editor5.so`。
    找到了 qt 的 fcitx5 輸入法模組：`/usr/lib/qt/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so`。
    找到未知的 fcitx qt 模組：`/usr/lib/qt6/plugins/plasma/kcms/systemsettings/kcm_fcitx5.so`。
    找到了 qt6 的 fcitx5 輸入法模組：`/usr/lib/qt6/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so`。

    下列錯誤也許並不准確，因為對 Qt 版本的猜測取決於發行版如何打包 Qt。如果您不使用任何對應版本的 Qt 程序，或者在 Wayland 下使用 Qt 的 text-input 支持，下列錯誤也不是嚴重問題。
    **找不到 Qt4 的 fcitx5 輸入法模組。**

## Gtk:
1.  gtk - `${GTK_IM_MODULE}`:

    **請設定環境變數 GTK_IM_MODULE 到「fcitx」，使用您的發行版提供的工具或加入 `export GTK_IM_MODULE=fcitx` 到您的 `~/.xprofile`。請參閱 [輸入法相關環境變數：GTK_IM_MODULE](http://fcitx-im.org/wiki/Input_method_related_environment_variables#GTK_IM_MODULE)。**

    **如果您的混成器完全支持 gtk使用的 text-input 協議，您也可以使用 gtk 內置的 Wayland 模塊。**

    使用 fcitx5-gtk2-immodule-probing 檢查目前環境下將被實際使用的輸入法模塊：

        GTK_IM_MODULE=xim

    使用 fcitx5-gtk3-immodule-probing 檢查目前環境下將被實際使用的輸入法模塊：

        GTK_IM_MODULE=wayland

    使用 fcitx5-gtk4-immodule-probing 檢查目前環境下將被實際使用的輸入法模塊：

        GTK_IM_MODULE=wayland

2.  `gtk-query-immodules`:

    1.  gtk 2:

        在 `/usr/bin/gtk-query-immodules-2.0` 找到 gtk `2.24.33` 的 `gtk-query-immodules`。
        版本行：

            # Created by /usr/bin/gtk-query-immodules-2.0 from gtk+-2.24.33

        找到了 gtk `2.24.33` 的 fcitx5 輸入法模組。

            "/usr/lib/gtk-2.0/2.10.0/immodules/im-fcitx5.so" 
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 

    2.  gtk 3:

        在 `/usr/bin/gtk-query-immodules-3.0` 找到 gtk `3.24.41` 的 `gtk-query-immodules`。
        版本行：

            # Created by /usr/bin/gtk-query-immodules-3.0 from gtk+-3.24.41

        找到了 gtk `3.24.41` 的 fcitx5 輸入法模組。

            "/usr/lib/gtk-3.0/3.0.0/immodules/im-fcitx5.so" 
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 

3.  Gtk 輸入法模組快取：

    1.  gtk 2:

        在 `/usr/lib/gtk-2.0/2.10.0/immodules.cache` 找到 gtk `2.24.33` 的輸入法模組快取。
        版本行：

            # Created by /usr/bin/gtk-query-immodules-2.0 from gtk+-2.24.33

        找到了 gtk `2.24.33` 的 fcitx5 輸入法模組。

            "/usr/lib/gtk-2.0/2.10.0/immodules/im-fcitx5.so" 
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 

    2.  gtk 3:

        在 `/usr/lib/gtk-3.0/3.0.0/immodules.cache` 找到 gtk `3.24.41` 的輸入法模組快取。
        版本行：

            # Created by /usr/bin/gtk-query-immodules-3.0 from gtk+-3.24.41

        找到了 gtk `3.24.41` 的 fcitx5 輸入法模組。

            "/usr/lib/gtk-3.0/3.0.0/immodules/im-fcitx5.so" 
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 

4.  Gtk 輸入法模組檔案：

    1.  gtk 2:

        所有找到的 gtk 2 輸入法模組檔案皆存在。

    2.  gtk 3:

        所有找到的 gtk 3 輸入法模組檔案皆存在。

    3.  gtk 4:

        所有找到的 gtk 4 輸入法模組檔案皆存在。

# 設定：
## Fcitx 附加元件：
1.  附加元件設定目錄：

    找到 fcitx5 附加元件設定目錄：`/usr/share/fcitx5/addon`。

2.  附加元件清單：

    1.  找到 22 個啟用的附加元件：

            Chewing 5.1.2
            Classic User Interface 5.1.9
            Clipboard 5.1.9
            DBus 5.1.9
            DBus Frontend 5.1.9
            Emoji 5.1.9
            Fcitx4 Frontend 5.1.9
            IBus Frontend 5.1.9
            Input method selector 5.1.9
            Keyboard 5.1.9
            KDE Input Method Panel 5.1.9
            Mozc 
            Status Notifier 5.1.9
            Notification 5.1.9
            Quick Phrase 5.1.9
            Spell 5.1.9
            Unicode 5.1.9
            DBus Virtual Keyboard 5.1.9
            Wayland 5.1.9
            Wayland Input method frontend 5.1.9
            XCB 5.1.9
            X Input Method Frontend 5.1.9

    2.  找到 0 個停用的附加元件：

3.  附加元件函式庫：

    找到了所有附加元件的函式庫。

4.  使用者介面：

    找到 3 個啟用的使用者介面附加元件：

        Classic User Interface
        KDE Input Method Panel
        DBus Virtual Keyboard

## 輸入法：
1.  `/home/user/.config/fcitx5/profile`:

        [Groups/0]
        # Group Name
        Name=預設
        # Layout
        Default Layout=us
        # Default Input Method
        DefaultIM=chewing

        [Groups/0/Items/0]
        # Name
        Name=keyboard-us
        # Layout
        Layout=

        [Groups/0/Items/1]
        # Name
        Name=chewing
        # Layout
        Layout=

        [Groups/0/Items/2]
        # Name
        Name=mozc
        # Layout
        Layout=

        [GroupOrder]
        0=預設

# 日誌：
1.  `date`:

        西元2024年04月28日 (週日) 09時28分12秒 CST

2.  `/home/user/.config/fcitx5/crash.log`:

    找不到 `/home/user/.config/fcitx5/crash.log`。

**警告：fcitx5-diagnose 輸出包含敏感訊息，包括發行版名稱、內核版本、正在執行程式的名稱... 等。**

**儘管這些訊息對開發人員的診斷有幫助，但在公開發佈到網上之前，請仔細檢查並根據需要刪除信息。**
```

**Additional context**

**Comment by wengxt** [comment] 2024-04-28 01:57
Duplicate of fcitx/fcitx5-chewing#17

**Comment by tobiichi3227** [comment] 2024-04-28 02:04
Oh, Sorry.
I didn't find that this issues has already been reported.

**Comment by wengxt** [comment] 2024-04-28 02:29
> Oh, Sorry. I didn't find that this issues has already been reported.

No, no need to be sorry about this. Triaging bug is job for devs, not for users.

**Closed by wengxt** 2024-04-28 02:29 UTC
