### ISSUE TITLE
fcitx5-mozc + GoogleChrome(GTK) text-box malfunction

### ISSUE THREAD

**Issue by stken2050** [fcitx/fcitx5#598] opened 2022-09-12 08:40 UTC
**Describe the bug**
fcitx5-mozc Japanese input has a malfunction on the Text box of GoogleChrome web-app .

It automatically converts after certain consequent types and becomes nearly impossible to type correctly.

![image](https://user-images.githubusercontent.com/1316994/189604758-6d2476b0-7a0a-44ab-a286-67d76c6fb345.png)

**To Reproduce**
1. Open https://mail.google.com/chat  or https://youtu.be/8XDmLr6wb4M  **on Google-Chrome (Opening in Firefox does not have this problem)**
2. Type `aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa` on the Text box.

**Expected behavior**

![image](https://user-images.githubusercontent.com/1316994/189605782-a05f61df-caa3-44d5-96ab-f71543ac9c56.png)

It should not convert unless a user types conversion-key.

**Unexpected behavior**

![image](https://user-images.githubusercontent.com/1316994/189606505-753a7bdf-b13a-490f-a661-46e6ee898b4e.png)

It forces to convert after a certain sequence of types.

For simplicity, the example to reproduce uses the type sequences of `a`; however, any type sequence has produce the problem.

**Desktop (please complete the following information):**
 - Desktop: Gnome / Arch-linux
 - Display server type: Wayland
 - The output of fcitx5-diagnose if possible.

```
 fcitx5-diagnose
# System Info:
1.  `uname -a`:

        Linux archlinux 5.15.67-1-lts #1 SMP Thu, 08 Sep 2022 12:59:52 +0000 x86_64 GNU/Linux

2.  `lsb_release`:

    `lsb_release` not found.

3.  `/etc/lsb-release`:

    `/etc/lsb-release` not found.

4.  `/etc/os-release`:

        NAME="Arch Linux"
        PRETTY_NAME="Arch Linux"
        ID=arch
        BUILD_ID=rolling
        ANSI_COLOR="38;2;23;147;209"
        HOME_URL="https://archlinux.org/"
        DOCUMENTATION_URL="https://wiki.archlinux.org/"
        SUPPORT_URL="https://bbs.archlinux.org/"
        BUG_REPORT_URL="https://bugs.archlinux.org/"
        LOGO=archlinux-logo

5.  Desktop Environment:

    Desktop environment is `gnome3`.

6.  XDG SESSION TYPE:

        XDG_SESSION_TYPE='wayland'

7.  Bash Version:

        BASH_VERSION='5.1.16(1)-release'

# Environment:
1.  DISPLAY:

        DISPLAY=':0'


        WAYLAND_DISPLAY='wayland-0'

2.  Keyboard Layout:

    1.  `setxkbmap`:

            WARNING: Running setxkbmap against an XWayland server
            xkb_keymap {
            	xkb_keycodes  { include "evdev+aliases(qwerty)"	};
            	xkb_types     { include "complete"	};
            	xkb_compat    { include "complete"	};
            	xkb_symbols   { include "pc+us+inet(evdev)+level3(menu_switch)+ctrl(nocaps)+terminate(ctrl_alt_bksp)"	};
            	xkb_geometry  { include "pc(pc105)"	};
            };

    2.  `xprop`:

            _XKB_RULES_NAMES(STRING) = "evdev", "pc105", "us", "", "terminate:ctrl_alt_bksp,ctrl:nocaps,lv3:menu_switch"

3.  Locale:

    1.  All locales:

            C
            C.UTF-8
            en_US.utf8
            POSIX

    2.  Current locale:

            LANG=en_US.UTF-8
            LC_CTYPE="en_US.UTF-8"
            LC_NUMERIC="en_US.UTF-8"
            LC_TIME="en_US.UTF-8"
            LC_COLLATE="en_US.UTF-8"
            LC_MONETARY="en_US.UTF-8"
            LC_MESSAGES="en_US.UTF-8"
            LC_PAPER="en_US.UTF-8"
            LC_NAME="en_US.UTF-8"
            LC_ADDRESS="en_US.UTF-8"
            LC_TELEPHONE="en_US.UTF-8"
            LC_MEASUREMENT="en_US.UTF-8"
            LC_IDENTIFICATION="en_US.UTF-8"
            LC_ALL=

4.  Directories:

    1.  Home:

            /home/ken

    2.  `${XDG_CONFIG_HOME}`:

        Environment variable `XDG_CONFIG_HOME` is not set.

        Current value of `XDG_CONFIG_HOME` is `~/.config` (`/home/ken/.config`).

    3.  Fcitx5 Settings Directory:

        Current fcitx5 settings directory is `~/.config/fcitx5` (`/home/ken/.config/fcitx5`).

5.  Current user:

    The script is run as ken (1000).

# Fcitx State:
1.  executable:

    Found fcitx5 at `/usr/bin/fcitx5`.

2.  version:

    Fcitx version: `5.0.19`

3.  process:

    Found 1 fcitx5 process:

           1504 fcitx5

4.  `fcitx5-remote`:

    `fcitx5-remote` works properly.

5.  DBus interface:

    Using `dbus-send` to check dbus.

    Owner of DBus name `org.fcitx.Fcitx5` is `:1.69`.

    PID of DBus name `org.fcitx.Fcitx5` owner is `1504`.

    Debug information from dbus:

           Group [x11::0] has 4 InputContext(s)
          IC [ffb2df97bee6450783ecca35a2894124] program:google-chrome frontend:dbus cap:6000000012 focus:0
          IC [782ea47c3f8b4df2b9317c90b5e7f216] program:google-chrome frontend:dbus cap:6000000012 focus:0
          IC [aa129e43e80e4a74aaa9cb2d1fd83117] program:code-insiders frontend:dbus cap:6000000012 focus:0
          IC [ef4c9fadbe9b462b9769abc5b0bca863] program:google-chrome frontend:dbus cap:6000000012 focus:0
        Group [wayland:] has 4 InputContext(s)
          IC [ee7c0e7acdb0405294fffa7696db0178] program:terminator frontend:dbus cap:e001000012 focus:1
          IC [2c6738c4b73146258e0a49940c17b1a7] program:terminator frontend:dbus cap:6001000012 focus:0
          IC [ae828d3e27274f5190209775458abfc2] program:terminator frontend:dbus cap:6001000012 focus:0
          IC [6f2ae1af0da04885a30c05c174b6fbf5] program: frontend:ibus cap:52 focus:0
        Input Context without group

# Fcitx Configure UI:
1.  Config Tool Wrapper:

    Found fcitx5-configtool at `/usr/bin/fcitx5-configtool`.

2.  Config GUI for qt:

    Found `fcitx5-config-qt` at `/usr/bin/fcitx5-config-qt`.

3.  Config GUI for kde:

    **`kcmshell5` not found.**

# Frontends setup:
## Xim:
1.  `${XMODIFIERS}`:

    **Environment variable XMODIFIERS is "@im=fcitx5" instead of "@im=fcitx". Please check if you have exported it incorrectly in any of your init files.**

    **Please set environment variable XMODIFIERS to "@im=fcitx" using the tool your distribution provides or add `export XMODIFIERS=@im=fcitx` to your `~/.xprofile`. See [Input Method Related Environment Variables: XMODIFIERS](http://fcitx-im.org/wiki/Input_method_related_environment_variables#XMODIFIERS).**

    Xim Server Name from Environment variable is fcitx5.

2.  XIM_SERVERS on root window:

    Xim server name is the same with that set in the environment variable.

## Qt:
1.  qt4 - `${QT4_IM_MODULE}`:

    **Environment variable QT_IM_MODULE is "fcitx5" instead of "fcitx". Please check if you have exported it incorrectly in any of your init files.**
    **You may have trouble using fcitx in qt4 programs.**

    **Please set environment variable QT_IM_MODULE to "fcitx" using the tool your distribution provides or add `export QT_IM_MODULE=fcitx` to your `~/.xprofile`. See [Input Method Related Environment Variables: QT_IM_MODULE](http://fcitx-im.org/wiki/Input_method_related_environment_variables#QT_IM_MODULE).**

2.  qt5 - `${QT_IM_MODULE}`:

    **Environment variable QT_IM_MODULE is "fcitx5" instead of "fcitx". Please check if you have exported it incorrectly in any of your init files.**
    **You may have trouble using fcitx in qt5 programs.**

    **Please set environment variable QT_IM_MODULE to "fcitx" using the tool your distribution provides or add `export QT_IM_MODULE=fcitx` to your `~/.xprofile`. See [Input Method Related Environment Variables: QT_IM_MODULE](http://fcitx-im.org/wiki/Input_method_related_environment_variables#QT_IM_MODULE).**

3.  Qt IM module files:

    Found fcitx5 im module for qt6: `/usr/lib/qt6/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so`.
    Found fcitx5 qt5 module: `/usr/lib/fcitx5/qt5/libfcitx-quickphrase-editor5.so`.
    Found unknown fcitx qt module: `/usr/lib/qt/plugins/kcms/kcm_fcitx5.so`.
    Found fcitx5 im module for qt: `/usr/lib/qt/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so`.
    **Cannot find fcitx5 input method module for Qt4.**

## Gtk:
1.  gtk - `${GTK_IM_MODULE}`:

    **Environment variable GTK_IM_MODULE is "fcitx5" instead of "fcitx". Please check if you have exported it incorrectly in any of your init files.**
    **You may have trouble using fcitx in gtk programs.**

    **Please set environment variable GTK_IM_MODULE to "fcitx" using the tool your distribution provides or add `export GTK_IM_MODULE=fcitx` to your `~/.xprofile`. See [Input Method Related Environment Variables: GTK_IM_MODULE](http://fcitx-im.org/wiki/Input_method_related_environment_variables#GTK_IM_MODULE).**

2.  `gtk-query-immodules`:

    1.  gtk 2:

        Found `gtk-query-immodules` for gtk `2.24.33` at `/usr/bin/gtk-query-immodules-2.0`.
        Version Line:

            # Created by /usr/bin/gtk-query-immodules-2.0 from gtk+-2.24.33

        Found fcitx5 im modules for gtk `2.24.33`.

            "/usr/lib/gtk-2.0/2.10.0/immodules/im-fcitx5.so" 
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 

    2.  gtk 3:

        Found `gtk-query-immodules` for gtk `3.24.34` at `/usr/bin/gtk-query-immodules-3.0`.
        Version Line:

            # Created by /usr/bin/gtk-query-immodules-3.0 from gtk+-3.24.34

        Found fcitx5 im modules for gtk `3.24.34`.

            "/usr/lib/gtk-3.0/3.0.0/immodules/im-fcitx5.so" 
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 

3.  Gtk IM module cache:

    1.  gtk 2:

        Found immodules cache for gtk `2.24.33` at `/usr/lib/gtk-2.0/2.10.0/immodules.cache`.
        Version Line:

            # Created by /usr/bin/gtk-query-immodules-2.0 from gtk+-2.24.33

        Found fcitx5 im modules for gtk `2.24.33`.

            "/usr/lib/gtk-2.0/2.10.0/immodules/im-fcitx5.so" 
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 

    2.  gtk 3:

        Found immodules cache for gtk `3.24.34` at `/usr/lib/gtk-3.0/3.0.0/immodules.cache`.
        Version Line:

            # Created by /usr/bin/gtk-query-immodules-3.0 from gtk+-3.24.34

        Found fcitx5 im modules for gtk `3.24.34`.

            "/usr/lib/gtk-3.0/3.0.0/immodules/im-fcitx5.so" 
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 

    3.  gtk 4:

        **Cannot find immodules cache for gtk 4**

        **Cannot find fcitx5 im module for gtk 4 in cache.**

4.  Gtk IM module files:

    1.  gtk 2:

        All found Gtk 2 immodule files exist.

    2.  gtk 3:

        All found Gtk 3 immodule files exist.

    3.  gtk 4:

        All found Gtk 4 immodule files exist.

# Configuration:
## Fcitx Addons:
1.  Addon Config Dir:

    Found fcitx5 addon config directory: `/usr/share/fcitx5/addon`.

2.  Addon List:

    1.  Found 20 enabled addons:

            Classic User Interface 5.0.19
            Clipboard 5.0.19
            DBus 5.0.19
            DBus Frontend 5.0.19
            Emoji 5.0.19
            Fcitx4 Frontend 5.0.19
            IBus Frontend 5.0.19
            Input method selector 5.0.19
            Keyboard 5.0.19
            KDE Input Method Panel 5.0.19
            Mozc 
            Status Notifier 5.0.19
            Notification 5.0.19
            Quick Phrase 5.0.19
            Spell 5.0.19
            Unicode 5.0.19
            Wayland 5.0.19
            Wayland Input method frontend 5.0.19
            XCB 5.0.19
            X Input Method Frontend 5.0.19

    2.  Found 0 disabled addons:

3.  Addon Libraries:

    All libraries for all addons are found.

4.  User Interface:

    Found 2 enabled user interface addons:

        Classic User Interface
        KDE Input Method Panel

## Input Methods:
1.  `/home/ken/.config/fcitx5/profile`:

        [Groups/0]
        # Group Name
        Name=Default
        # Layout
        Default Layout=us
        # Default Input Method
        DefaultIM=mozc

        [Groups/0/Items/0]
        # Name
        Name=keyboard-us
        # Layout
        Layout=

        [Groups/0/Items/1]
        # Name
        Name=mozc
        # Layout
        Layout=

        [GroupOrder]
        0=Default

# Log:
1.  `date`:

        Mon Sep 12 05:02:30 PM JST 2022

2.  `/home/ken/.config/fcitx5/crash.log`:

    `/home/ken/.config/fcitx5/crash.log` not found.

**Warning: the output of fcitx5-diagnose contains sensitive information, including the distribution name, kernel version, name of currently running programs, etc.**

**Though such information can be helpful to developers for diagnostic purpose, please double check and remove as necessary before posting it online publicly.**

```

**Additional context**

I did below following the instruction:
https://wiki.archlinux.org/title/Fcitx5#Integration

`nano /etc/environment `

```
GTK_IM_MODULE=fcitx5
QT_IM_MODULE=fcitx5
XMODIFIERS=@im=fcitx5
```

This bug has been for a while.

I have setup fcitx5-mozc many times from scratch after several clean installations of my Arch linux, so I'm pretty sure this bug is not avoidable in the standard configuration.

**Comment by zenfas** [comment] 2022-09-13 15:59
GTK_IM_MODULE=fcitx
QT_IM_MODULE=fcitx
XMODIFIERS=@im=fcitx

P/s: did you read the log message

**Comment by wengxt** [comment] 2022-09-14 03:10
I actually a little bit confused. because I can't reproduce with your issue.

I'm not sure if I understand your issue: You keep press a, but when you hit a certain length of input, the input is committed and prevent you from typing long sentence with mozc, is that correct?

Here's what I have on my system, seems ok
![图片](https://user-images.githubusercontent.com/259684/190049802-ca11a1b9-976b-46d5-8317-c496825f1534.png)

**Comment by stken2050** [comment] 2022-09-14 04:30
@zenfas  Sorry, I don't get it.
What do you mean exactly?

**Comment by zenfas** [comment] 2022-09-14 04:32
> @zenfas Sorry, I don't get it. What do you mean exactly?

you set wrong environment, should replace fcitx5 by fcitx only

**Comment by wengxt** [comment] 2022-09-14 04:42
@zenfas that shouldn't really matter for chrome. Firefox used to check fcitx(instead of fcitx5) to apply some fcitx specific hack, but I don't think chrome code has similar logic.

In short, set env to fcitx / fcitx5 shouldn't matter here.

**Comment by stken2050** [comment] 2022-09-14 04:43
@zenfas I don't know what's going on, but in many documents, including the official Arch Jp document.  it's described as `fcitx5` not `fcitx` 

https://wiki.archlinux.jp/index.php/Fcitx5#.E3.82.A4.E3.83.B3.E3.83.97.E3.83.83.E3.83.88.E3.83.A1.E3.82.BD.E3.83.83.E3.83.89.E3.83.A2.E3.82.B8.E3.83.A5.E3.83.BC.E3.83.AB.E3.81.AE.E7.92.B0.E5.A2.83.E5.A4.89.E6.95.B0.E3.81.AE.E8.A8.AD.E5.AE.9A

![image](https://user-images.githubusercontent.com/1316994/190060907-2aa5a281-cd30-4a00-9153-4f05233d07de.png)

In any way, I've changed back to `fcitx` from `fcitx5` in `/etc/environment`, but the result is the same.

![image](https://user-images.githubusercontent.com/1316994/190060680-836077e6-51b3-41ae-8752-c772a7ab3486.png)

The result is on YouTube comment on GoogleChrome.

**Comment by stken2050** [comment] 2022-09-14 04:48
@wengxt 

> You keep press a,   

Yes

> but when you hit a certain length of input, the input is committed

Yes, to be exact `aaaaaa.....` converts to `あああああああ` automatically (forcibly) without pushing the conversion-key.

 > and prevent you from typing long sentence with mozc, is that correct?

Actually, a user can keep typing, but after the malfunction, this behavior still keeps occurring in random timing, and the only way to avoid is hit the `Enter` key to get out the line.

**Comment by wengxt** [comment] 2022-09-14 04:54
@stken2050 can you run following command while reproducing the issue on your system? and copy paste the log to gist or sth else. You can do 
1. `sleep 5s; timeout 10s dbus-monitor  interface=org.fcitx.Fcitx.InputContext1`
2. before the first 5s passed, switch to chrome
3. try to type and reproduce it in chrome
4. wait till 10s passed and command ends before do anything else.

I probably need to try gnome to see if I can reproduce it. I'm on kde plasma wayland and doesn't have your problem.

**Comment by stken2050** [comment] 2022-09-14 05:09
@wengxt 

Thanks. I think I could capture the log for the malfunction.

https://gist.github.com/stken2050/6ac24f748ffbfbec685292cc7a82e6ef

**Comment by wengxt** [comment] 2022-09-14 23:46
method call time=1663131847.853154 sender=:1.83 -> destination=:1.67 serial=5709 path=/org/freedesktop/portal/inputcontext/1; interface=org.fcitx.Fcitx.InputContext1; member=FocusOut
signal time=1663131847.853212 sender=:1.67 -> destination=:1.83 serial=6490 path=/org/freedesktop/portal/inputcontext/1; interface=org.fcitx.Fcitx.InputContext1; member=CommitString
   string "ああああああああああああああああああああああああああああああああああああ"
signal time=1663131847.853337 sender=:1.67 -> destination=:1.83 serial=6491 path=/org/freedesktop/portal/inputcontext/1; interface=org.fcitx.Fcitx.InputContext1; member=UpdateFormattedPreedit
   array [
   ]
   int32 -1
method call time=1663131847.853561 sender=:1.83 -> destination=:1.67 serial=5710 path=/org/freedesktop/portal/inputcontext/1; interface=org.fcitx.Fcitx.InputContext1; member=FocusIn

So here's the cause, fcitx received FocusOut (normally, focus out means you switch to another application, or move cursor to another input box). That's what it trigger your issue. There's not much I can do on the fcitx side.

I could suggest some potential workaround:
1. ctrl+alt+P, this will toggle embedded preedit (underline text). If it's a chrome issue (or a webpage issue), it might work.
2. my chrome version is 105.0.5195.125, have you tried to upgrade chrome instead to see if helps?
3. Just in case if you already have some other desktop installed (if not, openbox might be a easy choice to try with). Can you try some other desktop to see if they have the same issue?
4. I'm also trying to understand if this is triggered by key event, or some background event. Can you try: type something not committed, then move your hand away and wait for a while, will the text be committed automatically?

Also, since you're using gnome-shell, do you have any extension installed?

**Comment by stken2050** [comment] 2022-09-15 05:30
Thanks for your investigations.

My Chrome version is Version 105.0.5195.125 (Official Build) (64-bit), so identical to yours.

The major reason I have chosen Gnome-Shell on Arch is in fact, stability, so I feel weird this happening now. After many trials to pursue the stability of the Linux desktop GUI environment, I found that Google-Chrome guys now develop their software on Gnome-Shell + Wayland, which makes sense because the default desktop environment of Ubuntu is currently Gnome-Shell Wayland.

I had been using Xorg+XFCE4 for a while, but the last year Google Chrome started crashing, and that is when I discovered X started dying because Ubuntu guys migrated to Gnome Wayland, and the same goes for Google guys, so I had stopped using Xorg+XFCE.

I liked KDE Plasma a lot and used it for a while, but as long as it's on X backend, the situation has been the same. Chrome keeps crushing, and also WM itself. 

[KDE plasma freezes all the time](https://forum.manjaro.org/t/kde-plasma-freezes-all-the-time/100537)
[Plasma keeps freezing, How to find what's going on?](https://forum.kde.org/viewtopic.php?f=289&t=166380)

Unfortunately, KDE Plasma+Wayland is still in pre-mature status, 
https://community.kde.org/Goals/Wayland
https://community.kde.org/Plasma/Wayland_Showstoppers
however, the X is collapsing now.

So I stopped using KDE and adopted Gnome-shell Wayland, and since then Chrome stops crashing and WM has been rock-solid, never crashed for months.

The good thing here is many extensions are available but surely as you mentioned, they can be the cause of instability, so I turned off the all now, but unfortunately, the result is the same.

I'm pretty sure that this issue will be gone if I switch to KDE Plasma or other WM because I know now this software is currently optimized to the KDE environment that you use. Software development really depends on the environment of the developer, and I'm not motivated to go back to KDE for the above reason.

I generally think this is a matter of optimization of the environment; however as you say this is due to Gnome-Shell + Google chrome because as I wrote, Firefox is without this medication. 
Thanks for your trial to understand, really, but I know this happens.

**Comment by stken2050** [comment] 2022-09-16 15:53
I do applogize for opening this issue.

After further investigation, it turns out that [grammarly](https://www.grammarly.com/) Chrome extension has been the cause of this problem. 
As @wengxt kindly investigated and mentioned there is nothing to do from fcitx5 side because the grammarly extension has intervend the typing and somewhat taken away the focus of input activity.

Since I synced Chrome setting as nowadays many users do, I never figured it's because of the extension, and that is the fundamental cause because Firefox does not have problem and only Chrome has.

Thanks and sorry again for your investigation.

**Closed** 2022-09-16 15:53 UTC
