### ISSUE TITLE
unable switch fcitx to any other language in calibre #517

### ISSUE THREAD

**Issue by wu-math-fan** [fcitx/fcitx5#548] opened 2022-07-18 18:55 UTC
https://www.mobileread.com/forums/showthread.php?t=347971
after reading:
https://fcitx-im.org/wiki/Input_method_related_environment_variables/zh-hans
https://fcitx-im.org/wiki/Configure_(Other)/zh-hans
https://fcitx-im.org/wiki/Setup_Fcitx_5#Binary_Qt_application
i added these to ~/.bash_profile:
GNU nano 5.4 .bash_profile
GNU nano 5.4 /etc/X11/xinit/xinput.d/fcitx
XIM=fcitx
XIM_PROGRAM=/usr/bin/fcitx
XIM_ARGS=""
XMODIFIERS DEFAULT=@im=fcitx
GTK_IM_MODULE=fcitx
QT_IM_MODULE=ibus
DEPENDS="fcitx"

after finished, i relogin. but the problem still remains.
the os is debian 11.
the desktop is kde plasma.
https://fcitx-im.org/wiki/Setup_Fcitx_5#.7E.2F.config.2Fplasma-workspace.2Fenv.2F.2A.sh
after adding ~/.config/plasma-workspace/env/im.sh
XMODIFIERS=@im=fcitx
GTK_IM_MODULE=fcitx
QT_IM_MODULE=ibus

the problem still remains

**Comment by wengxt** [comment] 2022-07-19 01:02
your script looks like fcitx4 file. So I don't know whether you're using fcitx4, or fcitx5. If it's fcitx4, It doesn't seems to be reasonable to report to fcitx 5 repo. But if you are using modern debian (like debian 9, 10, 11), don't bother to do your own customization on the file. Just run im-config and select fcitx (or fcitx5 if you're using fcitx5), and install all the fcitx{,5}-fontend-* package. For your case, it's should be fcitx{,5}-frontend-qt5.

If your calibre is from distro (Believe so, since I could find record on the web https://debian.pkgs.org/11/debian-main-amd64/calibre_5.12.0+dfsg-1+deb11u1_all.deb.html . If not, just switch to the deb version).

Also, as for instruction, always prefer distro wiki (https://wiki.debian.org/I18n/Fcitx5, or upstream wiki https://fcitx-im.org/wiki/Setup_Fcitx_5#im-config_.28Debian.2FDebian-based.2FUbuntu.29) instead of random post on the web.

To use fcitx{,5}-frontend-qt5 you need to make sure QT_IM_MODULE=fcitx

At least you should be able to test by executing  
```
QT_IM_MODULE=fcitx calibre
```
from shell directly to verify it can work.

**Comment by wengxt** [comment] 2022-07-19 01:05
I'll close it anyway since it's not a bug, but you may reply to this issue for any kind of question or support.

**Closed by wengxt** 2022-07-19 01:05 UTC
