### ISSUE TITLE
Keep default tray icon on default keyboard input

### ISSUE THREAD

**Issue by wiliamks** [fcitx/fcitx5#408] opened 2021-12-13 15:28 UTC
**Describe the bug**
Not exactly a bug, after I updated to 5.0.11 I noticed a weird behavior, before the default tray icon would appear when the default keyboard layout was selected, now, the default tray icon appears on startup, but as soon as I enter any kind of prompt it changes to the icon of the selected keyboard layout, so I want to ask, is this intended? If yes, is there a way to change it to the old behavior?

**To Reproduce**
On startup this icon shows up:
![2021-12-13-112604_31x32_scrot](https://user-images.githubusercontent.com/52431887/145839103-9d93a4a1-782a-4b3b-aa63-2843cee7f93f.png)

But after starting any type of app with a prompt, the default keyboard layout icon will show up
![2021-12-13-122355_26x21_scrot](https://user-images.githubusercontent.com/52431887/145839388-642092a3-b0b0-48ae-acf7-da6088153b4e.png)

**Expected behavior**
Keep showing default tray icon, unless it changes to other keyboard layout.

**Desktop (please complete the following information):**
 - Distro: EndeavourOS
 - Desktop: awesomeWM
 - Display server type: X11

**Comment by wiliamks** [comment] 2021-12-13 16:51
yes, exactly, before it would only show the layout name when the default one was not selected

**Comment by wengxt** [comment] 2021-12-13 17:57
1. no input window focused -> input-keyboard icon
2. only one layout configured in fcitx -> input-keyboard icon
3. more than two layout configured -> in order to distinguish between them,text label based icon is used.

If it matches those 3 conditions it's expected. But feel free to make suggestions on how fcitx can do it better.

Can you share ~/.config/fcitx5/profile ?

**Comment by wiliamks** [comment] 2021-12-13 18:17
if that is intended, then ok, because in version 5.0.10, it was not exactly like, the input-keyboard icon would show even when there were different keyboard layouts configured on the default keyboard layout, here is my ~/.config/fcitx5/profile

```
[Groups/0]
# Group Name
Name="Group 1"
# Layout
Default Layout=br-thinkpad
# Default Input Method
DefaultIM=mozc

[Groups/0/Items/0]
# Name
Name=keyboard-br-thinkpad
# Layout
Layout=

[Groups/0/Items/1]
# Name
Name=mozc
# Layout
Layout=

[Groups/1]
# Group Name
Name="Group 2"
# Layout
Default Layout=br-thinkpad
# Default Input Method
DefaultIM=keyboard-br-thinkpad

[Groups/1/Items/0]
# Name
Name=keyboard-br-thinkpad
# Layout
Layout=

[GroupOrder]
0="Group 2"
1="Group 1"

```

so one more question, is it possible to change the icon of a layout? In my case I would like keyboard-br-thinkpad icon to be the input-keyboard icon

**Comment by wengxt** [comment] 2021-12-13 18:27
Actually in your case, there's only br-thinkpad being used, in that case we should prefer input-keyboard. This does not match my expectation and should be fixed.

**Comment by wengxt** [comment] 2021-12-13 18:33
Em, but I can't reproduce your issue after apply you profile.

Can you check if ~/.config/fcitx5/conf/classicui.conf contains following line
```
PreferTextIcon=False
```
?

**Comment by wiliamks** [comment] 2021-12-13 18:40
wait, I actually now think that is not the issue, when I went to get the profile the default-layout of group 2 was "us", I changed it on the text editor to br-thinkpad, and rebooted the system to make sure it reloaded, it kept the same way, but when I checked again, it was still with "us", tried changing again, and for some reason every time I rebooted it would come back to "us", probably because my system is in american english, but I'm not sure, then I deleted the Group 2, and it started working as intended. Now my config looks like this:
```
[Groups/0]
# Group Name
Name="Group 1"
# Layout
Default Layout=br-thinkpad
# Default Input Method
DefaultIM=mozc

[Groups/0/Items/0]
# Name
Name=keyboard-br-thinkpad
# Layout
Layout=

[Groups/0/Items/1]
# Name
Name=mozc
# Layout
Layout=

[GroupOrder]
0="Group 1"
```
I don't know exactly where the issue is, but I solved my case here, so you can close this issue if you want

**Comment by wengxt** [comment] 2021-12-13 18:47
Ah, you shouldn't change it while fcitx's running. upon fcitx exits, it will write whatever content in the memory into the file. So your content is overwritten. Either, you use fcitx5-configtool to do that in GUI, or quit fcitx and then edit the file.

**Closed by wengxt** 2021-12-13 18:47 UTC
