### ISSUE TITLE
Strange behavior in certain Web rich text editors

### ISSUE THREAD

**Issue by kebugcheckex** [fcitx/fcitx5#338] opened 2021-09-15 04:52 UTC
**Describe the bug**
Fcitx behaves strangely when entering Chinese in [ProseMirror](https://prosemirror.net/) text editor.

**To Reproduce**
1. Open [ProseMirror](https://prosemirror.net/)
2. Delete any existing content in the rich text editor.
3. Set bold by clicking on the "B" icon, or press Ctrl+B.
4. Start typing Chinese using fcitx.

**Expected behavior**
Chinese text inputs normally.

**Actual behavior**
An extraneous character is entered before the ones I actually want to type. That character is the first one in the selection box for the first key press. For example, when I type "ceshi", I expect to see 测试. However, it actually enters 从测试, where 从 is the first character in the selection box when I press the C key. It behaves as if I press the spacebar immediately after pressing the first key.

**Desktop (please complete the following information):**
 - Desktop: KDE
 - Display server type: X11
 - The output of fcitx5-diagnose: see [gist](https://gist.github.com/kebugcheckex/1d232424ea884c78d31b26af02d97839)
 - Browser: Chrome (Chromium) and Opera, **not** in Firefox though.

**Additional context**
When set to bold, ProseMirror editor creates a `<strong>` HTML tag and moves the cursor into it. I suspect this movement of cursor somehow interferes with fcitx, causing it to think that the user pressed the spacebar or moved the cursor. Since this doesn't reproduce in other systems, it may be related to fcitx.

**Comment by wengxt** [comment] 2021-09-16 15:54
I tried to play with some different input method. It looks like the issue is triggered if preedit cursor is put at the beginning of the text. While we could put the preedit cursor at the real position (end of the text), it would make the input box moving around, which is not an desired behavior.

I don't know if there's anything else we could do, but I know two way to workaround:
1. check "Show preedit in application" option in Pinyin, with that checked, the preedit content will be in another mode and cursor will use a different pattern which won't trigger this issue.
2. Ctrl+Alt+P provides a temporary way to disable preedit.

Hope this helps.

**Closed by wengxt** 2021-09-16 15:54 UTC
